events {}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Serve static assets directly
    location /assets/ {
      try_files $uri =404;
    }

    # SPA fallback: always serve index.html so React Router can handle routes
    location / {
      try_files $uri /index.html;
    }
  }
}

